# Archivo de configuración para Jekyll - MÉTODO DE SOBRESCRITURA DE TEMA

# --- Configuración del Sitio ---
title: "Rodrigo Cabezas Zúñiga"
description: "Ingeniero en Control de Gestión & Data Scientist"
baseurl: ""
url: "https://rodrigocabezasz.github.io"

# --- Opciones del Tema (que nuestro tema local usará) ---
author: "Rodrigo Cabezas Zúñiga"
copyright_name: "Rodrigo Cabezas Zúñiga"
email: "rorocabezas@gmail.com"
locale: "es-ES"

# Enlaces de la Barra de Navegación (Header)
navbar-links:
  Mi CV: "/"
  Blog: "/blog"
  GitHub: "https://github.com/rodrigocabezasz"
  LinkedIn: "https://www.linkedin.com/in/rodrigo-cabezas-zuñiga-698a8532"
  


# --- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  
# --- Paginación del Blog ---
paginate: 5
paginate_path: "/blog/page:num/"

