
# Configuración del sitio para Clean Blog
title: "Rodrigo Cabezas Zúñiga"
description: "Ingeniero en Control de Gestión & Data Scientist"
baseurl: ""
url: "https://rodrigocabezasz.github.io"

# Información del autor
author: "Rodrigo Cabezas Zúñiga"
copyright_name: "Rodrigo Cabezas Zúñiga"
email: "rorocabezas@gmail.com"
locale: "es-ES"


# --- ESTRUCTURA DE URLS (PERMALINKS) ---
# Esto asegura que las páginas se creen como /blog/ en lugar de /blog.html
permalink: pretty

# Enlaces de la Barra de Navegación (Header)
# Asegúrate de que la indentación sea correcta (dos espacios por nivel)
navbar-links:
  - title: Mi CV
    url: /
  - title: Blog
    url: /blog/
  - title: Categorías
    url: /categories/
  - title: Contacto
    url: /contact/
  - title: GitHub
    url: https://github.com/rodrigocabezasz
  - title: LinkedIn
    url: https://www.linkedin.com/in/rodrigocabezasz/ # URL más limpia
    #https://www.linkedin.com/in/rodrigo-cabezas-zuñiga-698a8532


# --- Plugins y Paginación ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  
paginate: 5 # Número de posts por página
paginate_path: "/blog/page:num/"

# Excluir archivos innecesarios del build final
exclude:
  - Gemfile
  - Gemfile.lock
