# Archivo de configuración para Jekyll - Tema "Clean Blog"

# --- Configuración del Sitio ---
title: "Rodrigo Cabezas Zúñiga" # El tema lo usa para el header principal y la pestaña del navegador
description: "Ingeniero en Control de Gestión & Data Scientist" # Este será tu subtítulo
baseurl: ""
url: "https://rodrigocabezasz.github.io"

# --- Configuración del Tema "Clean Blog" ---
# Esto le dice a GitHub qué tema usar
theme: jekyll-theme-clean-blog

# Opciones del tema
author: "Rodrigo Cabezas Zúñiga"
copyright_name: "Rodrigo Cabezas Zúñiga"
email: "rorocabezas@gmail.com"
locale: "es-ES" # Para que algunas fechas salgan en español

# Enlaces de la Barra de Navegación (Header)
navbar-links:
  Mi CV: "/"
  Blog: "/blog" # Crearemos esta página a continuación
  GitHub: "https://github.com/rodrigocabezasz"
  LinkedIn: "https://www.linkedin.com/in/rodrigo-cabezas-zuñiga-698a8532"

# --- Plugins ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate # Necesario para el blog

# --- Paginación del Blog ---
paginate: 5 # Número de posts por página
paginate_path: "/blog/page:num/"