
# Configuración del sitio para Clean Blog
title: "Rodrigo Cabezas Zúñiga"
description: "Ingeniero en Control de Gestión & Data Scientist"
baseurl: ""
url: "https://rodrigocabezasz.github.io"

# Información del autor
author: "Rodrigo Cabezas Zúñiga"
copyright_name: "Rodrigo Cabezas Zúñiga"
email: "rorocabezas@gmail.com"
locale: "es-ES"

# Navegación principal
navbar-links:
  CV: "/"
  Blog: "/blog"
  Contacto: "/contact" 
  GitHub: "https://github.com/rodrigocabezasz"
  LinkedIn: "https://www.linkedin.com/in/rodrigo-cabezas-zuñiga-698a8532"

# --- Plugins y Paginación ---
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  
paginate: 5 # Número de posts por página
paginate_path: "/blog/page:num/"
