
# Configuración del sitio para Clean Blog
title: "Rodrigo Cabezas Zúñiga"
description: "Ingeniero en Control de Gestión & Data Scientist"
baseurl: ""
url: "https://rodrigocabezasz.github.io"

# Plugins recomendados
plugins:
  - jekyll-feed

author: "Rodrigo Cabezas Zúñiga"
email: "rorocabezas@gmail.com"
locale: "es-ES"

# Navegación principal
navbar-links:
  CV: "/"
  Blog: "/blog"
  GitHub: "https://github.com/rodrigocabezasz"
  LinkedIn: "https://www.linkedin.com/in/rodrigo-cabezas-zuñiga-698a8532"

